livewire/docs

- pages/events.md
- pages/registering_components.md
Fixed namespace of Livewire facade when registering components. Otherwise the user will receive the error:
> Class 'App\Providers\Livewire' not found
Also removed the duplicated message **This method is twice as fast as Method B, so it is the preffered usage.** under the Method B itself.
> Minor fixes

- build_production/docs/component-basics/index.html
- build_production/docs/data-binding/index.html
- build_production/docs/events/index.html
- build_production/docs/input-validation/index.html
- build_production/docs/lifecycle-hooks/index.html
- build_production/docs/quickstart/index.html
- build_production/docs/redirecting/index.html
- build_production/docs/rendering-components/index.html
- build_production/docs/spa-mode/index.html
- build_production/docs/testing/index.html
- build_production/index.html
- source/docs/component-basics.blade.md
- source/docs/data-binding.blade.md
- source/docs/events.blade.md
- source/docs/input-validation.blade.md
- source/docs/lifecycle-hooks.blade.md
- source/docs/quickstart.blade.md
- source/docs/redirecting.blade.md
- source/docs/rendering-components.blade.md
- source/docs/spa-mode.blade.md
- source/docs/testing.blade.md
- source/index.blade.php
Rename all `LivewireComponent` occurrences to `Component` and add import statements.
The [current version](https://livewire-framework.com/docs/rendering-components/) of the docs say you need to extend `LivewireComponent`
But it should be extending `Component` instead:
\* The colors are off because of compression, I didn't change that :p
> Fix component extends

- source/docs/index.blade.php
I always type `/docs` out and get a 404 error page. This just redirects it to quickstart 👍
> added redirect /docs => /docs/quickstart

- source/docs/spa-mode.blade.md
If I understood the https://github.com/calebporzio/livewire/releases/tag/v0.2.2 changelog and https://github.com/calebporzio/livewire/commit/6ba2eb928778b3b3f5bf5aba5d9a49582ee43bd0#diff-afbbb6430c73cf50cafea78549c61fd9R81 correct those docs need to be updated.
> add `start()` call to SPA docs

- source/docs/polling.blade.md
Polling is reduced to 5% and not stopped when the browser tab is in the background.
> Polling is reduced not stopped when in background

- source/docs/testing.blade.md
Right now, the example shown throws will throw a 
`Livewire\Exceptions\ProtectedPropertyBindingException`
Per the source this is the correct method of setting a public property in a unit test.
> Fixed example to use the current rule for setting properties

- source/docs/installation.blade.md
- Remove quotation marks from config keys.
- Wrap default values in `code` formatting, as they appear in `config/livewire.php`. 
- Update copy for consistency.
Hope you don't mind me doing micro-PRs btw! Thought it would be easier when deciding what you want and don't want to merge in.
> Update config options table on Installation page

- source/docs/spa-mode.blade.md
Since public properties are automatically passed to the javascript, the example will cause the following error:
```
Livewire component's [show-contact] public property [contact] must be of type: [numeric, string, array, null, or boolean]. Only protected or private properties can be set as other types because JavaScript doesn't need to access them.
```
I think making the `$contact` variable `protected` will make the example work.
> Fixing a wrong example

- source/docs/input-validation.blade.md
Without the `.prevent` it will reload the page and error instead of letting Livewire handle the request.
> use wire:submit.prevent for input validation example

- source/docs/making-components.blade.md
When reading the docs like a book (but skipping the quickstart), there is no mention of how you actually render the Livewire component until the mount() method page. I think it makes sense to introduce this concept here.
This resolves the issue number 324 in the livewire/livewire repository.
> Add information on rendering components

- package-lock.json
- package.json
- source/_assets/js/main.js
- source/_layouts/base.blade.php
- source/_layouts/documentation.blade.php
- source/_layouts/master.blade.php
- source/_nav/menu-toggle.blade.php
Fixes #76 
I've also added Alpine (dogfooding...). Wanted to do a tiny transition when opening the menu but that's harder than I imagined. Can't use `x-show` since it only needs to apply to small screens. Without `x-show`, `x-transition` won't work.
If you prefer without alpine, let me know and I'll stip that. If you do like it, I'll be happy to PR the other ones.
Also, some class lists got re-ordered to follow a unofficial Tailwind standard (vscode plugin). If you dislike this, let me know and I'll refactor.
> Fixing mobile menu

- source/docs/polling.blade.md
According to the source code https://github.com/livewire/livewire/blob/a2789a7aa594681e3493ee92449b47b3605e9418/js/component/Polling.js#L26
the default polling interval is 2 seconds
> Correct the default polling interval

- source/docs/loading-states.blade.md
I'm not sure whether this is an officially supported feature :)
However from the current docs it wasn't clear that this is possible, I only found it trough trying. If this functionality is intended it would be great to have it in the docs.
> Add documentation for wire:model loading state

- source/index.blade.php
Filename of the component is `search-users.blade.php`. Therefore it should be called as `livewire.search-users`
> Fixed return view in index.blade.php

- resources/views/docs/nesting-components.blade.php
The Laravel 7 tag syntax is mentioned right in the next paragraph, so this one seems to be unnecessary and duplicate.
> Remove duplication from nested component page

- resources/views/docs/testing.blade.php
In [testing](https://laravel-livewire.com/docs/testing) example, post does not have a `name`, it has a `title`.
> Change name to title in testing.

- resources/views/docs/redirecting.blade.php
All redirection point to `foo` this one was pointing to `food`  🍔
> Food to foo

- resources/views/docs/installation.blade.php
- `its` -> possessive, the JS portion in this sentence belongs to Livewire
- `it's` -> shorter version of `it is`
> Correct minor grammar issue in installation instructions

- resources/views/docs/making-components.blade.php
Fix comment because `make:livewire foo` generates a `Foo.php` instead of `Foo/Bar.php`.
> Fix comment

- resources/views/docs/alpine-js.blade.php
Missing apostrophe on 
<input x-data @input.keydown.enter="@this.set('foo', 'bar)"> and 
<input x-data @input.keydown.enter="window.livewire.find('unique-id').set('foo', 'bar)">
> Missing apostrophes in AlpineJS section

- resources/views/docs/pagination.blade.php
On the Pagination documentation page, there is a spelling mistake. Anchor is mentioned as "achor". Fixed that.
> Fixed a spelling mistake in the Pagination page.

- resources/views/includes/screencast-sidebar.blade.php
What it says on the tin, you can now click the sidebar link even between the scrrencast title and its duration. Or even on the duration.
> [UI] Make entire line clickable in screencast sidebar menu

- resources/views/docs/events.blade.php
The biggest fix (which is, albeit, one character) is fixing this:
Additionally, added "you" in a few sentences that make them read a little better.
> Fix typos in the events docs.

- resources/views/docs/properties.blade.php
Currently, Livewire doesn't support PHP typed properties (in the language since [PHP 7.4](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties)), but there isn't a note about that on the "Properties" page of the docs. This PR adds that note.
Also noticed that there must have used to be three important notes, because the section said "here are _three_ ESSENTIAL things...", so no change had to be made there!
I tried to capture the current feel of the documentation that's around this new note, but I'm open to discussion if something feels off about it!
> Add note to Properties page about not currently supporting PHP typed properties

- resources/views/docs/testing.blade.php
- `assertSeeLivewire()` - checks for component presence on a page.
- `assertSeeHtml()` - checks for presence of raw HTML.
- `assertDontSeeHtml()` - checks for absence of raw HTML.
> Add missing test facilities

- resources/views/docs/rendering-components.blade.php
I was looking for this and couldn't find it anywhere listed in the docs. Sub-folder namespacing is only mentioned I the `move` command docs and does not show how to render components with such.
> Added docs for namespace'd components

- tests/Feature/RoutesTest.php
Currently every PR is failing tests due to missing SIMPLECAST_API_KEY
Unless we add a test simplecast account and key or imitate proper response with a list of podcasts, this will always fail.
So i propose we skip this assertion unless the key is set, this way @calebporzio can still test it in his local environment where he probably has the SIMPLECAST_API_KEY set.
> Only test podcasts if the env variable for SIMPLECAST_API_KEY is set

- resources/views/docs/properties.blade.php
If the public properties are set to the "uncast" versions, we get exceptions when trying to uncast an uncasted value. 
For example when setting a field to cast as collection we get `Call to a member function toArray() on array`
> Initiate custom cast properties to avoid exceptions

- app/DocumentationPages.php
The Inline Scripts page is missing form the menu. I added it inside the JS Integration but can be changed as you see fit.
> Adds the missing Inline Scripts page inside JS Integrations

- resources/views/docs/properties.blade.php
Currently, the documentation only provides information on using an associative array with the `fill` method. This adds documentation and a code example on using an Eloquent model with the `fill` method.
> Adds documentation for filling using an eloquent model.

- resources/views/includes/screencast-sidebar.blade.php
Right now the play button shrinks if there is not enough space. It would be better if it has the same size on all episodes.
> Fix Play Symbol in screencasts sidebar

- resources/views/docs/api.blade.php
Add missing `wire:model.lazy="foo"` 
- Runs the "foo" method on the component when user clicks away from the input field.
> Add wire:model.lazy API

- resources/views/docs/2/upgrading.blade.php
Missing quotation mark in a PHP codeblock
> Fix missing quote in upgrade docs

- resources/views/docs/2/upgrading.blade.php
`property of message` implies that it's `message.response`
> response.message -> message.response

- resources/views/docs/2/rendering-components.blade.php
Looks like two references to `Route::livewire()` were missed in the v2 docs.
I'm hoping this is the correct replacement - I'm actually having some issues with route parameters using `Route::get()`, but I'll create a separate issue in the main repo for that.
> Update old references to Route::livewire()

- resources/views/docs/2/upgrading.blade.php
There doesn't seem to be an equivalent hook in V2, so noting it in the upgrade guide in case anyone goes looking for it
> Note that the beforeDomUpdate hook was removed in V2

- resources/views/docs/2/properties.blade.php
Changed "durastically" to "drastically".
(Because I'm pedantic).
> Fix typo on "Properties" page (docs v2)

- resources/views/docs/2/troubleshooting.blade.php
I've had encountered problems with the `query string` feature of Livewire on my blog. @nuernbergerA helped me to backtrace it to the `security headers` which I set in my application.
The `referrer-policy` is the one that caused the problem. It needs to be set to `same-origin` to make it work with Livewire's query string.
I thought it might be a good idea to add that information to the docs.
> Add query string troubleshooting section

- resources/views/docs/2/quickstart.blade.php
First commit includes the following changes.
- added the new blade component syntax in the "Include Component" text
- added the old `@livewire` blade directive in the "Include Component" code
- removed the text 'or "-" button' in "View it in browser" text, which
is not present in the corresponding Code
> Fixed Inconsistencies in the 2.x Docs

- resources/views/docs/2/nesting-components.blade.php
Fixed typo in Nesting Components - https://laravel-livewire.com/docs/2.x/nesting-components
`reqires` updated to `requires`
> Fix typo in v2 nesting components

- resources/views/docs/2/input-validation.blade.php
Hey there, I reworded the code comments in the "Direct Error Message Manipulation" section to be placed above the lines they're referencing, clarified a line on getting an error bag instance, and fixed a typo that was present!
> Clarify Validation "Direct Error Message Manipulation" code comments

- resources/views/docs/1/loading-states.blade.php
- resources/views/docs/2/loading-states.blade.php
Add missing `delay` modifier documentation for `wire:loading` directive. Fix https://github.com/livewire/docs/issues/252
> Add missing wire:loading.delay modifier documentation

- resources/views/docs/1/input-validation.blade.php
- resources/views/docs/1/nesting-components.blade.php
- resources/views/docs/2/input-validation.blade.php
- resources/views/docs/2/polling.blade.php
I noticed that a couple new features since v2 haven't been documented, and wanted to add them to the docs so people who don't follow the project as closely can take advantage of them too. 
Let me know if there's a better way to explain any of these things!
> Document wire:poll.keep-alive and $validationAttributes

- resources/views/livewire/screencast-player.blade.php
This PR fixes these errors when a user isn't a sponsor and tries to view a sponsor-only video.
> Don't new up a Vimeo player when the video isn't shown

- resources/views/docs/1/artisan-commands.blade.php
- resources/views/docs/2/artisan-commands.blade.php
For consistency throughout the docs, I've added the self closing slash on this page where it did not exist.
> Add self closing slash to L7 component 

- resources/views/includes/search-input.blade.php
I was looking at #233 and noticed that this feature is actually already added, but there is no indication to the user. I updated the placeholder in the search input to the same wording as the Tailwind docs: Search the docs (Press "/" to focus)
> Add message to placeholder in search input

- resources/views/includes/search-input.blade.php
- resources/views/layouts/documentation.blade.php
- routes/web.php
This will make the docsearch input only show results from V2 instead of showing duplicate entries from V1 and V2.
I've submitted a PR to update the Algolia configuration [here](https://github.com/algolia/docsearch-configs/pull/2652), but it seems to be working already.
> Add Algolia docs versioning

- alpine-js.blade.php
Corrected a few spelling and grammar mistakes in the this section of the docs
> Grammar/Spelling in alpine-js.blade.php

- traits.blade.php
sortBy should only be reassigned after the direction is determined else you'll always just be reversing
> Fix sort  direction logical issue

- events.blade.php
Hello there.&nbsp; 👋
I was reading the documentation and noticed the `Scoping To Parent Listeners` subheading was a level too high.
This PR aims to fix that issue by downgrading the heading one level down to an `h3`.
I've included screenshots of the issue and the potential fix. 🙂
> Fix "Scoping To Parent Listeners" heading level.

- input-validation.blade.php
Hi again.&nbsp; 👋
While browsing the documentation I found a typo in the starting paragraph under the **Validation**  section.
This PR fixes remedies that by adding a missing `$this` in front of that inline code block.
With this PR it will match the inline code block inside the first paragraph after **Real-time Validation**.
> Add missing $this variable in front of `->validate()` inline code block.

- alpine-js.blade.php
Me again. 😀
Found a typo while reading about using **AlpineJS** with **Livewire**, thought I'd submit a PR for it.
> Fix typo in "Accessing Livewire Directives From Blade Components" section.

- alpine-js.blade.php
* "its" (possesive) was intended. "it's" is always a contraction for the words "it is"
* "info" was meant instead of "into"
* Words that begin with a vowel sound should be preceded with "an"
> [2.x] Proofread alpine-js

- properties.blade.php
Added a new important note regarding Livewire properties.
I struggled with this a little while and didn't find out what the problem was until I started tracing the code in the vendor folder. I had a property/model that was not behaving as expected. I set a `messages` property which was a Collection of chat messages but Livewire was using it to set custom validation messages; but since the Validator factory requires the messages variable to be an array and my messages was a collection, it was giving me an error every time I tried to execute the `$this->validate()` function. 
It seems obvious in retrospect but I updated the Important Notes section to include this because it can be a gotcha. There also needs to be a single list we can refer to that includes all the properties we cannot use …
> Property/model names cannot conflict with properties reserved for Livewire

- testing.blade.php
Hey there.&nbsp; 👏
I noticed when testing with Livewire that a useful assertion, namely the `assertDontSeeLivewire` assertion isn't written about anywhere in the documentation, I only found out about it when looking through the source to see how `assertSeeLivewire` was made. 🙂
This PR adds a test including said assertion just below the latter one to show that such a helper method does indeed exist.
Neither of the methods exists in the reference on testing helpers either so I'm wondering should I add both to the reference in another PR @calebporzio?
> Add assertDontSeeLivewire assertion to testing

- reference.blade.php
Hello.&nbsp; 👏
This PR adds the PHPUnit helpers methods to the reference page, they seem to be a bit hidden so thought it'd be a good idea to add them to the reference page as I mentioned in #311. 🙂
> Add missing PHPUnit helpers to testing methods on reference page

- installation.blade.php
Not sure if you planned to write this section, and not sure if I have put it correctly (Laravel is in `require-dev`, not exactly sure why), but I'm just suggesting to add a similar few lines. 
Cause I received a few questions on my Youtube videos about Livewire, like: "This works with laravel 7.x? and php 7.2?" [link to the comment](https://www.youtube.com/watch?v=q7V56AdyK0Y&lc=UgyMJJl9nDcviWQmdvN4AaABAg)
> Requirements Section in Installation

- loading-states.blade.php
Added an example for targeting actions with parameters (https://github.com/livewire/livewire/pull/2189).
Also split the "models" thing into its own section, let me know if you want all three under the same heading instead, thanks!
> add loading target actions with parameters

- input-validation.blade.php
- query-string.blade.php
Added info about `getRules()` and `getQueryString()` getter methods just like for the [event listeners](https://laravel-livewire.com/docs/2.x/events#event-listeners).
> Add info about getRules() and getQueryString() methods

- troubleshooting.blade.php
After speaking to @GertjanRoke, I didn't realise that elements needed a root dom element. This led me to experience an issuer where only one element on my page would allow me to run my function, whereas the others wouldn't do anything at all.
Also to this, is there a possibility of being able to add a warning when not specifying a root element, as this could be something someone misses -  I myself missed this completely somehow through the docs.
Hopefully this change within the documentation will cover what is needed, as it could help for those going to the troubleshooting page.
> Added information for no root element

- lifecycle-hooks.blade.php
- reference.blade.php
- Clarify when the hydrateFoo lifecycle hook runs
- Sync up the lifecycle hooks into the reference list, copying the order and adding missing hooks
> Updated hook reference

- lifecycle-hooks.blade.php
I ran into an issue where my updated lifecycle hook was not working properly, and then I got led even further astray because the docs state that multiword lifecycle hook names are for targeting nested properties, with no mention anywhere (as far as I'm aware) of how to target camel case or pascal case properties.
> Add how to use lifecycle hooks with multiword property names

- pagination.blade.php
The example of the "default livewire paginator" doesn't actually use livewire or the wire:click="nextPage" features.
Replaced the example code with the current version of simple-tailwind.blade.php as a true example of how the default livewire paginator works!
> Fix default pagination example

- lifecycle-hooks.blade.php
Based on the discussion on the issue livewire/livewire#2687.
> Add direct property mutation warning into the Lifecycle Hooks page

- loading-states.blade.php
It seems like the documentation is missing the `block` modifier for `wire:loading`.
However, it is working just fine in a Livewire component.
> Add wire:loading.block

- reference.blade.php
Changes:
"A a significant of Livewire's core uses..."
To:
"A a significant portion of Livewire's core uses..."
> Add a missing word to Javascript Hooks docs.
