livewire/docs

- source/docs/data-binding.blade.md
the correct variable name is `name` and not `todo`
> Fix variable name

- source/docs/installation.blade.md
I actually tried to install it :p
EDIT: 
Sorry, it's my first time using Jigsaw. Should I build the site with `npm run production` and also push the `build_production` dir? I did that on this other PR https://github.com/calebporzio/livewire-docs/pull/8
Hmm I think I should, cause I can't see the changes here https://deploy-preview-7--goofy-tereshkova-ff1e2b.netlify.com/docs/installation/
> Add a note about the NPM package not being available yet

- build_production/docs/testing/index.html
- source/docs/testing.blade.md
Updated the 2nd failing test after v0.0.6 was pushed. Works flawlessly now.
> Fix expected assertions

- navigation.php
- source/docs/security.blade.md
Add docs for https://github.com/calebporzio/livewire/pull/44
> Add docs for Livewire::filterMiddleware()

- source/docs/custom-javascript.blade.md
Typo in closing `@endwarning` blade directive 😎
> Fix custom-javascript page not rendering correctly

- source/docs/loading-states.blade.md
There was a minor typo. The word "but" should be "by"
> Fixed typo "but" should be "by"

- source/docs/testing.blade.md
> initializing component properties during testing

- source/docs/component-basics.blade.md
- source/docs/redirecting.blade.md
* Update component-basics.blade.md
* Update redirecting.blade.md
> Update docs to show support for Laravel redirect (#1)

- source/docs/events.blade.md
Update the docs to show that you can send parameters through the event bus.
> Send Parameters with Events

- source/docs/installation.blade.md
Goes with https://github.com/calebporzio/livewire/pull/241.
I also renamed "Include the PHP" to "Install the package".
> Add publishing assets section

- source/docs/inline-scripts.blade.md
Related to https://github.com/livewire/livewire/issues/320
> Clarification about scripts being run only once.

- source/_layouts/base.blade.php
**BEFORE -> AFTER**
No need for them to be there, amiriiiiight?
> Strip HTML from <title> tags

- source/_layouts/base.blade.php
Use the snippet from further down:
```
@if ($page->production)
@endif
```
and wrap Googles tracking in it.
> Load Google Analytics only in production

- source/docs/render-method.blade.md
Don't know if you want this to be a documented feature or a pleasant hidden surprise, but I threw something together. Feel free to update copy to match your tone, because I'm not a native Livewire Developer™️ speaker. 
Or just close if you don't want it cluttering up the docs. Peace! ✌️
> Add section explaining default render() method on parent Component

- source/docs/pagination.blade.md
The `WithPagination` trait is provided by Livewire, not Laravel.
> Fix statement about the WithPagination trait

- source/docs/the-livewire-developer.blade.md
I've updated a few tiny things on the "The Livewire Developer" page to correct some grammar.
Sorry I'm so pedantic. 🙃
> Fix grammar and flow mistakes.

- source/_layouts/master.blade.php
Change "I'll ship you sticker" to "I'll ship you a sticker"
> Fix wording on sponsorship

- source/docs/state-management.blade.md
...So folks don't have to dive into vendor to figure it out.
> Add use statement for Castable

- source/index.blade.php
Changed counter to search user in filenames
> Fixed files names in code example of homepage

- source/docs/properties.blade.md
Well there is not more to say.. only thanks for this great framework! 👍
> Added a missing comma at the end of the line

- source/docs/spa-mode.blade.md
Related Livewire PR: https://github.com/livewire/livewire/pull/693
I was thinking about adding an extra section for it, but I think it's totally fine to show the possibility inside the existing code block. Let me know if you want to see it extracted into an extra paragraph 🚀
> Extended docs: Providing layout parameters

- source/docs/properties.blade.md
The first code sample is missing a closing }
> Add missing } in properties.blade.md

- resources/views/docs/properties.blade.php
https://github.com/livewire/docs/issues/119
> Correct example on keeping a clean query string

- resources/views/docs/making-components.blade.php
Thought we should document an example of using `Livewire::component`. Let me know if you think it belongs in another spot, thanks!
> added example of Livewire::component usage

- resources/views/docs/alpine-js.blade.php
> Fix blade component syntax in alpine.js doc page

- resources/views/docs/troubleshooting.blade.php
Hello Caleb, some people are getting some checksum issues and I think it's smart to at why this happens to the docs. I know you like to see what the PR is about in the message but I think it's better if you read the change.
By the way, English is not my native language but I did my best to write it as clear as I could, feel free to change it, no feelings will be hurt 😘
This also counts for the styling and example.
The main point is that I think it should be added to the docs to save people some time.
If you have any questions feel free to leave a comment.
> Added a new section to troubleshooting for checksum issues

- resources/views/docs/alpine-js.blade.php
Adds missing closing apostrophe
> Fixing code typo in AlpineJS section

- resources/views/docs/nesting-components.blade.php
- resources/views/docs/troubleshooting.blade.php
Documented the array syntax for parameters in a couple of places where it had been missed.
> Parameter array syntax

- resources/views/docs/nesting-components.blade.php
> Revert "Update nesting-components"

- resources/views/docs/events.blade.php
This function is at the minute undocumented but has appeared in a few forums. Hopefully this will save some people time in the future.
Here is a time where it's been mentioned in an issue on the main repo, [link](https://github.com/livewire/livewire/issues/830#issuecomment-617269130).
I have included an example with AlpineJS as I think it is incredibly useful for this. I'm not sure of another way to acheive this solution so I think that it is relevant.
> Add documentation for dispatchBrowserEvents

- resources/views/docs/file-uploads.blade.php
I think this is a typo. Just fix a very small typo.
> Fixed typo handing to handling on file upload

- resources/views/docs/loading-states.blade.php
I've edited some of the language for clarity.
> Edit Loading States page for clarity

- resources/views/docs/troubleshooting.blade.php
Changed  ..."elements that been changed"  to "elements that have been changed"
> Fixed grammatical error in  troubleshooting.blade.php

- resources/views/docs/properties.blade.php
I had problems with non-persisted models and had to debug to find out they are not natively supported.
Using a custom caster fixed the problem.
> Detail how to handle non-persisted models.

- resources/views/docs/file-uploads.blade.php
I used my absolute top tier developing skills for this contribution.
> Fix broken link

- resources/views/docs/alpine-js.blade.php
- resources/views/docs/flash-messages.blade.php
- resources/views/docs/laravel-echo.blade.php
- resources/views/docs/rendering-components.blade.php
* Correcting "it's" --> "its"
* Wording change in Echo docs for clarity
> Small grammar and wording tweaks

- resources/views/home.blade.php
* fix snorkel
* fix Pikaday
* fix word order for grammar
* fix some punctuation to eliminate run-on sentences
> spelling and grammar fixes for homepage

- resources/views/docs/2/upgrading.blade.php
Just a few fixes for the upgrade page now that V2 has been released. All are aesthetic; none change the content of the docs.
> small grammar fixes

- resources/views/docs/2/inline-scripts.blade.php
Following the issue https://github.com/livewire/livewire/issues/1600
> Use livewire:load instead of DOMContentLoaded

- resources/views/docs/2/input-validation.blade.php
Just find this out after seeing a PR about custom attribute.
I think this one is missing, maybe.
> add custom validation error message & attribute docs

- resources/views/docs/1/lifecycle-hooks.blade.php
- resources/views/docs/2/lifecycle-hooks.blade.php
> Add a note on update hooks not being run from actions

- resources/views/docs/2/testing.blade.php
Documents [livewire/liveiwre#1735](https://github.com/livewire/livewire/pull/1735). This should be merged after the next version is tagged.
> Document the `assertViewIs` testing method

- resources/views/docs/2/rendering-components.blade.php
Fix typo  in V2 of rendering-components.blade.php
> Fix typo  in V2 of rendering-components.blade.php

- composer.json
- composer.lock
- resources/views/docs/1/alpine-js.blade.php
- resources/views/docs/1/file-uploads.blade.php
- resources/views/docs/2/alpine-js.blade.php
- resources/views/docs/2/file-uploads.blade.php
- resources/views/layouts/base.blade.php
- resources/views/livewire/screencast-player.blade.php
Upgrades Livewire to v2 and Alpine to v2.7.0. Also fixes failing tests.
> Upgrade Livewire and Alpine

- resources/views/docs/2/lifecycle-hooks.blade.php
Found the information in the upgrade guide as a replacement for custom casters but couldn't find any information anywhere else, so thought to best add it here.
Hope this helps!
> Update lifecycle hooks doc to include property de/hydration

- installation.blade.php
Add's the --config flag to the publish config file instructions inline with changes that were merged in PR https://github.com/livewire/livewire/pull/1836
> Update publishing config instructions

- pagination.blade.php
This is related to PR https://github.com/livewire/livewire/pull/1942 which adds the option to publish pagination views.
> Update pagination doc to include pagination command

- pagination.blade.php
* Fix a very small typo of a word that should not be capitalized
> [2.x] Proofread pagination

- file-uploads.blade.php
Update `storeAs` function description and parameter, to match the rest of descriptions.
> Normalize store as function description

- query-string.blade.php
It's not Livewire related and only a small thing, but might a good thing to get the search type for input fields better known and more widely used in world wide dood :-)
> Change input type to search

- rendering-components.blade.php
Adds documentation for https://github.com/livewire/livewire/pull/2247/files
> document new layout config

- alpine-js.blade.php
not sure if intended to be generically talking about *A* show property. Arguably more clear to be specific about the actual property name (?)
> Describing property show -> showDropdown (section about sharing state)

- reference.blade.php
- testing.blade.php
Add assertCount to testing and reference docs, relating to [Add assert count to tests](https://github.com/livewire/livewire/pull/2495)
> Add assertCount to docs

- traits.blade.php
Fixed Syntax error of trait example.
> Fixed Syntax error of trait example

- lifecycle-hooks.blade.php
I think the title says it all.
> Properties of the updating and updated hooks were in the wrong order

- testing.blade.php
Based on the discussion on the issue livewire/livewire#2688.
> Add a testing example for components with passed data

- pagination.blade.php
> Update the number of ways to customize the pagination

- testing.blade.php
Removed extra @verbatim directive on section "Testing Components With Passed Data"
> Removed extra @verbatim directive

- testing.blade.php
Add the new test method ["assertNoRedirect"](https://github.com/livewire/livewire/pull/2864) to the list.
> Add the assertNoRedirect / testing method

- file-uploads.blade.php
Found a typo while reading the docs it's a very minor one, fixed it.
> Fixed a typo

- lifecycle-hooks.blade.php
I have tried to add specific details for array hooks. 
My language is far from perfect, but at least this might help people to find the answer quicker without testing components live as I had to in this case
Related discussion: https://github.com/livewire/livewire/discussions/3241
> Add details to updating/updated hooks for arrays

- loading-states.blade.php
- quickstart.blade.php
Fixes a couple of lang props passed to the code component.
> [2.x] Fix some Blade highlighting

- testing.blade.php
Reference: https://github.com/livewire/livewire/pull/3628
> add documentation for toggle testing method
